name: Build, Push and Deploy Docker Image
on: [push]

env:
  IMAGE_NAME: ghcr.io/cacapretty/nginx-simple-app

permissions:
  contents: read
  packages: write

jobs:
  build-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Build Image
        run: docker build -t $IMAGE_NAME .

      - name: Login to GitHub Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u cacapretty --password-stdin

      - name: Push Image
        run: docker push $IMAGE_NAME

  deploy:
    needs: build-push-image
    runs-on: ubuntu-latest
    steps:
      - name: Pull image
        run: docker pull $IMAGE_NAME

      - name: Run container
        run: docker run -d -p 8080:80 --name app $IMAGE_NAME

      - name: Check container
        run: curl localhost:8080
